CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID bigint NOT NULL AUTO_INCREMENT,
    EMAIL varchar(100) NOT NULL UNIQUE,
    NAME varchar(100) NOT NULL,
    BIRTH varchar(100) NOT NULL,
    PHONE varchar(100) NOT NULL,
    PRIMARY KEY (MEMBER_ID)
);
CREATE TABLE IF NOT EXISTS QUESTION (
    QUESTION_ID bigint NOT NULL AUTO_INCREMENT,
    MEMBER_ID bigint NOT NULL,
    TITLE varchar(100) NOT NULL UNIQUE,
    BODY varchar(100) NOT NULL,
    PRIMARY KEY (QUESTION_ID)
);
CREATE TABLE IF NOT EXISTS ANSWER (
    ANSWER_ID bigint NOT NULL AUTO_INCREMENT,
    MEMBER_ID bigint NOT NULL,
    QUESTION_ID bigint NOT NULL,
    BODY varchar(100) NOT NULL UNIQUE,
    PRIMARY KEY (ANSWER_ID)
);