server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test&useLegacyDatetimeCode=false
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

#관리자 이메일 정의

mail:
  address:
    admin: admin@gmail.com
