server:
  port: 8080
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    url: jdbc:mysql://preproject-database-deploy.cjhwdv5mjrgd.ap-northeast-2.rds.amazonaws.com:13306/test?serverTimezone=UTC
    username: admin
    password: qwer1234!
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
#    username: root
#    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

config:
  domain: http://preproject-bucket-029.s3-website.ap-northeast-2.amazonaws.com

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420